### PR TITLE
add possibility to pass in a Wire instance

### PR DESCRIPTION
**Pull request by SunboX**
This adds the possibility to pass in a Wire instance to be able to configure the clock speed / frequency and also the used IO pins.

### CODE REVIEW

**Comment by ladyada** [comment]
looks good! what hardware did you test with?

**Comment by SunboX** [comment]
Thanks! I tested with an ESP32 Deb Kit from AZ-Delivery and an MCP23017 Expansion Board from Waveshare

**Comment by ladyada** [comment]
do you have an AVR board like UNO to check with?

**Comment by SunboX** [comment]
I have to look into my box, but I might have none.

**Comment by ladyada** [comment]
ok please do :) that will help a lot!

**Comment by SunboX** [comment]
Ok, found one in one of my boxes. Will test it tomorrow.
IMG_20200810_214831

**Comment by ladyada** [comment]
perfect :)

**Comment by SunboX** [comment]
Ok, I tested it using an Arduino Uno and set the clock speed to 400khz. Here's my test code:
```c++
#include <Wire.h>
#include "Adafruit_MCP23017.h"

Adafruit_MCP23017 mcp;

void setup() {

    Wire.setClock(400000); // set frequency to 400khz

    mcp.begin(7, &Wire);

    mcp.pinMode(5, OUTPUT);
    mcp.digitalWrite(5, HIGH);
}

void loop() {

    delay(5000);

    mcp.digitalWrite(5, LOW);

    delay(5000);

    mcp.digitalWrite(5, HIGH);
}
```

And here's a video showing the test:
https://youtu.be/4aTDRAySRF4

Sadly I have no oscilloscope, so I could not validate if it runs @ 400khz.

**Comment by ladyada** [comment]
sounds good, thanks!

**Comment by SunboX** [comment]
Thanks a lot!

**Pull request merged**
