### PR TITLE
Add support for INPUT_PULLUP in function pinMode()

### PR DESCRIPTION
**Pull request by agambier**
Add support for MCP23017 pull-up resistors.

The function modePin() has been modified to support standard INPUT_PULLUP mode.
Tested and validated.

### CODE REVIEW

**Comment by agambier** [comment]
Nobody's interested by this feature ?

**Comment by gerciljunio** [comment]
I am, it seems to me that there is another PR here open for this function, but nobody releases anything! 😢

**Comment by gerciljunio** [comment]
> Nobody's interested by this feature ?

 I am, it seems to me that there is another PR here open for this function, but nobody releases anything! 😢

**Comment by siddacious** [comment]
@agambier @gerciljunio This is a good feature! Thank you for your contribution. I'll get hardware soon to test however adding an example that uses this feature would help get it tested and merged asap.

Thank you for your patience. We've got 1200+ repos and there are only two of us that review/merge on top of our other responsibilities. Any help in making that easier is appreciated!

**Comment by richteel** [comment]
@agambier, I just made a similar change and just noticed your check-in. Your code should take few clock cycles then the code I checked in. I like how you implemented. Hopefully one of our changes get accepted as I'm surprised it was not addressed a while ago. This does need to be fixed. I'm currently using it in a keypad for a project I'm working on.

**Comment by agambier** [comment]
@richteel Thanks.
I wrote this more than a year ago and now with the master branch it seems there's a conflict that must be fixed before the merge.
It's not a complicated conflict to fix but only people with write access can do it. :(

**Comment by agambier** [comment]
> Thank you for your patience. We've got 1200+ repos and there are only two of us that review/merge on top of our other responsibilities. Any help in making that easier is appreciated!

@siddacious I totaly understand you guys are busy. What kind of help do you need ? I mean what else can I do to help you ? for example for this PR ?

**Comment by caternuson** [comment]
Thanks for the PR. We just made a major update to this library:
https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/releases/tag/2.0.0
Please update to that, try it out, and open a new feature request issue if needed.

**Pull request closed without merging**
