### PR TITLE
HW Address pins support

### PR DESCRIPTION
**Pull request by maziu**
Hi,

I needed support for HW addressing for MCP23S17 (SPI) chip so I implemented it.
Change is not breaking API, default argument was added to begin_spi method, so old code using this library will work.

User may pass 3rg argument to begin_spi method to use HW addressing:
mcpchip.begin_SPI(MCP_DOOR_CS, &SPI, 0b100); 
If no argument is provided address 0 is used (as up to now).

To enable HW addressing on MCP23S17 chip, bit in config register must be set, and this can be done by invoking method enableAddrPins();

One note: There is HW bug in the MCP23S17 chip related to HW addressing that is described in "errata note". My commit also takes it into account. As a result, enableAddrPins() must write bit twice (to devices with addr 0b0xx and 0b1xx separately).

I checked it on MCP23S17 chip with different HW addresses (0b000, 0b0xx, 0b1xx).
It should work for MCP23S08 also, however I didn't have chip to test it.

### CODE REVIEW

**Comment by maziu** [comment]
I fixed doxygen issue, however I completely don't understand why clang-format fails. There is no error message shown

**Comment by ladyada** [comment]
clang output is here
https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/runs/4482144705?check_suite_focus=true
its easiest to run clang format locally
https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format

**Comment by maziu** [comment]
Fixed the formatting and squashed all fixes into single commit (together with feature) to keep single commit on main repo. Sorry for force push, I assumed that this is best way.

**Comment by caternuson** [comment]
@maziu Can you link to the errata note that talks about needing to sending the IOCON setting twice.

Also curious how one would use this in a real setup. Is the idea all the MCPs are setup with address pins A0, A1, A2 wired as desired. At power on, they'll all have IOCON.HAEN disabled and be address A2=A1=A0=0:
image
image

Then a single SPI xfer is done that all MCPs receive to enable IOCON.HAEN. From that point forward, all MCP SPI xfers must use each MCPs specific address?

The MCP23S17's have two "ports" with separate register banks for each. So, there is IOCONA and IOCONB. What happens if only IOCONA.HAEN is set and not IOCONB.HAEN?

Also curious why this SPI hardware addressing is a useful feature. Does it save on CS pins when total number of MCPs is more than few?

**Comment by maziu** [comment]
Sure, here is the errata: http://ww1.microchip.com/downloads/en/DeviceDoc/80311a.pdf
image

There are two banks, but only single IOCON register for both (look that it does not have A/B at the end like other registers)
image

 `Also curious how one would use this in a real setup. Is the idea all the MCPs are setup with address pins A0, A1, A2 wired as desired. At power on, they'll all have IOCON.HAEN disabled and be address A2=A1=A0=0. Then a single SPI xfer is done that all MCPs receive to enable IOCON.HAEN. From that point forward, all MCP SPI xfers must use each MCPs specific address?`

Normally yes, but due to mentioned bug in HW, IOCON.HAEN must be send/set twice: to address 0b1xx and 0b0xx, otherwise it will be not set in the device with A2 = 1. After setting HAEN all further communication must contain correct specific device address.

Please note, that due to mentioned HW bug, if you tie A2 to HIGH, then any communication to chip must be done with addr 0b1xx, even if  you have HAEN disabled.

So my proposed function enableAddrPins() is setting HAEN twice - for address 0b000 and selected device address, effectively enabling this bit for all devices on the bus, if selected address starts with 0b1xx.

Purpose of HW addressing is to reduce number of CS pins required. Usually it's not needed, but I had to program such board that had different ADDR pins set HW designed, so I had to add support for it.

**Comment by caternuson** [comment]
Cool. Thanks for the additional info. Gonna merge!

**Pull request merged**
