### PR TITLE
Support INPUT_PULLUP for pinmode(uint8_t pin, uint8_t mode)

### PR DESCRIPTION
**Pull request by euphi**
+ also added debug code for I2C errors when reading GPIO, define
MCP23017_Serial_Debug to activate
+ bumped patch version in library.properties (1.0.3 -> 1.0.4)

--> See #23

### CODE REVIEW

**Comment by Daemach** [comment]
I need this.  Please merge asap.

**Comment by ladyada** [comment]
@euphi @Daemach please remove the "#ifdef MCP23017_Serial_Debug" debug code from the PR and we'll try it out!

**Comment by nicocesar** [comment]
is almost a year later, and no news here. 

I'm trying to have all inputs into an ESP8266 with INPUT_PULLUPs and seems that this library is not the best fit.

**Comment by caternuson** [comment]
Thanks for the PR. This should be taken care of with the 2.0.0 release:
https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/releases/tag/2.0.0

**Pull request closed without merging**
